.TH "AddSurveyAction" 3 "Sun May 8 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AddSurveyAction \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBrun\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "run ()"
Traite les données envoyées par le formulaire d'ajout de sondage\&.
.PP
Si l'utilisateur n'est pas connecté, un message lui demandant de se connecter est affiché\&.
.PP
Sinon, la fonction ajoute le sondage à la base de données\&. Elle transforme les réponses et la question à l'aide de la fonction PHP 'htmlentities' pour éviter que du code exécutable ne soit inséré dans la base de données et affiché par la suite\&.
.PP
Un des messages suivants doivent être affichés à l'utilisateur :
.IP "\(bu" 2
'c';
.IP "\(bu" 2
'Il faut saisir au moins 2 réponses\&.';
.IP "\(bu" 2
'Merci, nous avons ajouté votre sondage\&.'\&.
.PP
.PP
Le visiteur est finalement envoyé vers le formulaire d'ajout de sondage en cas d'erreur ou vers une vue affichant le message 'Merci, nous avons ajouté votre sondage\&.'\&.
.PP
\fBSee also:\fP
.RS 4
\fBAction::run()\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
