.TH "C:/wamp/www/ProjetPhp/views/templates/addsurveyform.inc.php" 3 "Sun May 8 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/wamp/www/ProjetPhp/views/templates/addsurveyform.inc.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgenerateInputForResponse\fP ($n)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "generateInputForResponse ( $n)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
