.TH "C:/wamp/www/ProjetPhp/views Directory Reference" 3 "Sun May 8 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/wamp/www/ProjetPhp/views Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBtemplates\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAddSurveyFormView\&.inc\&.php\fP"
.br
.ti -1c
.RI "file \fBDefaultView\&.inc\&.php\fP"
.br
.ti -1c
.RI "file \fBMessageView\&.inc\&.php\fP"
.br
.ti -1c
.RI "file \fBSignUpFormView\&.inc\&.php\fP"
.br
.ti -1c
.RI "file \fBSurveysView\&.inc\&.php\fP"
.br
.ti -1c
.RI "file \fBUpdateUserFormView\&.inc\&.php\fP"
.br
.ti -1c
.RI "file \fBView\&.inc\&.php\fP"
.br
.in -1c
