.TH "C:/wamp/www/ProjetPhp Directory Reference" 3 "Sun May 8 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/wamp/www/ProjetPhp Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBactions\fP"
.br
.ti -1c
.RI "directory \fBdoc\fP"
.br
.ti -1c
.RI "directory \fBJS\fP"
.br
.ti -1c
.RI "directory \fBlib\fP"
.br
.ti -1c
.RI "directory \fBmodel\fP"
.br
.ti -1c
.RI "directory \fBviews\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBindex\&.php\fP"
.br
.in -1c
