.TH "C:/wamp/www/ProjetPhp/model Directory Reference" 3 "Sun May 8 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/wamp/www/ProjetPhp/model Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDatabase\&.inc\&.php\fP"
.br
.ti -1c
.RI "file \fBResponse\&.inc\&.php\fP"
.br
.ti -1c
.RI "file \fBSurvey\&.inc\&.php\fP"
.br
.in -1c
