.TH "C:/wamp/www/ProjetPhp/doc/search/classes_8.js" 3 "Sun May 8 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/wamp/www/ProjetPhp/doc/search/classes_8.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['view',['View',['\&.\&./class_view\&.html',1,'']]],
  ['voteaction',['VoteAction',['\&.\&./class_vote_action\&.html',1,'']]]
]
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
