.TH "Database" 3 "Sun May 8 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Database \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.ti -1c
.RI "\fBcheckPassword\fP ($nickname, $password)"
.br
.ti -1c
.RI "\fBgetUserFromId\fP ($user_id)"
.br
.ti -1c
.RI "\fBaddUser\fP ($nickname, $password)"
.br
.ti -1c
.RI "\fBaddComm\fP ($comm, $survId, $login)"
.br
.ti -1c
.RI "\fBupdateUser\fP ($nickname, $password)"
.br
.ti -1c
.RI "\fBsaveSurvey\fP ($survey)"
.br
.ti -1c
.RI "\fBloadSurveysByOwner\fP ($owner)"
.br
.ti -1c
.RI "\fBloadCommBySurvey\fP ($survey)"
.br
.ti -1c
.RI "\fBloadSurveysByKeyword\fP ($keyword)"
.br
.ti -1c
.RI "\fBloadAllSurveys\fP ()"
.br
.ti -1c
.RI "\fBvote\fP ($id, $surveyId)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ()"
Ouvre la base de données\&. Si la base n'existe pas elle est créée à l'aide de la méthode createDataBase()\&. 
.SH "Member Function Documentation"
.PP 
.SS "addComm ( $comm,  $survId,  $login)"

.SS "addUser ( $nickname,  $password)"
Ajoute un nouveau compte utilisateur si le pseudonyme est valide et disponible et si le mot de passe est valide\&. La méthode peut retourner un des messages d'erreur
.PP
\fBParameters:\fP
.RS 4
\fI$nickname\fP Pseudonyme\&. 
.br
\fI$password\fP Mot de passe\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean|string True si le couple a été ajouté avec succès, un message d'erreur sinon\&. 
.RE
.PP

.SS "checkPassword ( $nickname,  $password)"
Vérifie qu'un couple (pseudonyme, mot de passe) est correct\&.
.PP
\fBParameters:\fP
.RS 4
\fI$nickname\fP Pseudonyme\&. 
.br
\fI$password\fP Mot de passe\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean True si le couple est correct, false sinon\&. 
.RE
.PP

.SS "getUserFromId ( $user_id)"
Récupère un Nickname depuis un ID d'user\&.
.PP
\fBParameters:\fP
.RS 4
\fI$user_id\fP ID d'user\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
string retourne le nickname\&. 
.RE
.PP

.SS "loadAllSurveys ()"
Charge TOUS les sondages, pour les afficher sur la page d'accueil\&. Tri du plus récent au plus ancien\&. 
.PP
\fBReturns:\fP
.RS 4
array(Survey)|boolean Sondages trouvés par la fonction ou false si une erreur s'est produite\&. 
.RE
.PP

.SS "loadCommBySurvey ( $survey)"
Charge l'ensemble des commantaires d'un sondage\&.
.PP
\fBParameters:\fP
.RS 4
\fI$survey\fP id du sondage\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
array(Survey)|boolean Sondages trouvés par la fonction ou false si une erreur s'est produite\&. 
.RE
.PP

.SS "loadSurveysByKeyword ( $keyword)"
Charge l'ensemble des sondages dont la question contient un mot clé\&.
.PP
\fBParameters:\fP
.RS 4
\fI$keyword\fP Mot clé à chercher\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
array(Survey)|boolean Sondages trouvés par la fonction ou false si une erreur s'est produite\&. 
.RE
.PP

.SS "loadSurveysByOwner ( $owner)"
Charge l'ensemble des sondages créés par un utilisateur\&.
.PP
\fBParameters:\fP
.RS 4
\fI$owner\fP Pseudonyme de l'utilisateur\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
array(Survey)|boolean Sondages trouvés par la fonction ou false si une erreur s'est produite\&. 
.RE
.PP

.SS "saveSurvey ( $survey)"
Sauvegarde un sondage dans la base de donnée et met à jour les indentifiants du sondage et des réponses\&.
.PP
\fBParameters:\fP
.RS 4
\fI$survey\fP Sondage à sauvegarder\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean True si la sauvegarde a été réalisée avec succès, false sinon\&. 
.RE
.PP

.SS "updateUser ( $nickname,  $password)"
Change le mot de passe d'un utilisateur\&. La fonction vérifie si le mot de passe est valide\&. S'il ne l'est pas, la fonction retourne le texte 'Le mot de passe doit contenir entre 3 et 10 caractères\&.'\&. Sinon, le mot de passe est modifié en base de données et la fonction retourne true\&.
.PP
\fBParameters:\fP
.RS 4
\fI$nickname\fP Pseudonyme de l'utilisateur\&. 
.br
\fI$password\fP Nouveau mot de passe\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean|string True si le mot de passe a été modifié, un message d'erreur sinon\&. 
.RE
.PP

.SS "vote ( $id,  $surveyId)"
Vérifie si une IP n'a pas déja voté et Enregistre le vote pour la réponse\&.
.PP
\fBParameters:\fP
.RS 4
\fI$id\fP Identifiant de la réponse\&. 
.br
\fI$surveyId\fP Identifiant du sondage\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean True si le vote a été enregistré, false sinon\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
