.TH "DefaultView" 3 "Sun May 8 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DefaultView \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBView\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBdisplayBody\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "displayBody ()\fC [protected]\fP"
Affiche une page sans contenu\&.
.PP
\fBSee also:\fP
.RS 4
\fBView::displayBody()\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
