.TH "C:/wamp/www/ProjetPhp/index.php" 3 "Sun May 8 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/wamp/www/ProjetPhp/index.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgetActionByName\fP ($name)"
.br
.ti -1c
.RI "\fBgetViewByName\fP ($name)"
.br
.ti -1c
.RI "\fBgetAction\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$action\fP = \fBgetAction\fP()"
.br
.ti -1c
.RI "\fB$view\fP = $action\->getView()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "getAction ()"

.SS "getActionByName ( $name)"

.SS "getViewByName ( $name)"

.SH "Variable Documentation"
.PP 
.SS "$action = \fBgetAction\fP()"

.SS "$view = $action\->getView()"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
