.TH "C:/wamp/www/ProjetPhp/doc/navtree.js" 3 "Sun May 8 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/wamp/www/ProjetPhp/doc/navtree.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBgetData\fP (varName)"
.br
.ti -1c
.RI "function \fBstripPath\fP (uri)"
.br
.ti -1c
.RI "function \fBstripPath2\fP (uri)"
.br
.ti -1c
.RI "function \fBhashValue\fP ()"
.br
.ti -1c
.RI "function \fBhashUrl\fP ()"
.br
.ti -1c
.RI "function \fBpathName\fP ()"
.br
.ti -1c
.RI "function \fBlocalStorageSupported\fP ()"
.br
.ti -1c
.RI "function \fBstoreLink\fP (link)"
.br
.ti -1c
.RI "function \fBdeleteLink\fP ()"
.br
.ti -1c
.RI "function \fBcachedLink\fP ()"
.br
.ti -1c
.RI "function \fBgetScript\fP (scriptName, func, show)"
.br
.ti -1c
.RI "function \fBcreateIndent\fP (o, domNode, node, level)"
.br
.ti -1c
.RI "function \fBgotoAnchor\fP (anchor, aname, updateLocation)"
.br
.ti -1c
.RI "function \fBnewNode\fP (o, po, text, link, childrenData, lastNode)"
.br
.ti -1c
.RI "function \fBshowRoot\fP ()"
.br
.ti -1c
.RI "function \fBexpandNode\fP (o, node, imm, \fBshowRoot\fP)"
.br
.ti -1c
.RI "function \fBglowEffect\fP (n, duration)"
.br
.ti -1c
.RI "function \fBhighlightAnchor\fP ()"
.br
.ti -1c
.RI "function \fBselectAndHighlight\fP (hash, n)"
.br
.ti -1c
.RI "function \fBshowNode\fP (o, node, index, hash)"
.br
.ti -1c
.RI "function \fBremoveToInsertLater\fP (element)"
.br
.ti -1c
.RI "function \fBgetNode\fP (o, po)"
.br
.ti -1c
.RI "function \fBgotoNode\fP (o, subIndex, root, hash, relpath)"
.br
.ti -1c
.RI "function \fBnavTo\fP (o, root, hash, relpath)"
.br
.ti -1c
.RI "function \fBshowSyncOff\fP (n, relpath)"
.br
.ti -1c
.RI "function \fBshowSyncOn\fP (n, relpath)"
.br
.ti -1c
.RI "function \fBtoggleSyncButton\fP (relpath)"
.br
.ti -1c
.RI "function \fBinitNavTree\fP (toroot, relpath)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBnavTreeSubIndices\fP = new Array()"
.br
.ti -1c
.RI "var \fBanimationInProgress\fP = false"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "function cachedLink ()"

.SS "function createIndent ( o,  domNode,  node,  level)"

.SS "function deleteLink ()"

.SS "function expandNode ( o,  node,  imm,  showRoot)"

.SS "function getData ( varName)"

.SS "function getNode ( o,  po)"

.SS "function getScript ( scriptName,  func,  show)"

.SS "function glowEffect ( n,  duration)"

.SS "function gotoAnchor ( anchor,  aname,  updateLocation)"

.SS "function gotoNode ( o,  subIndex,  root,  hash,  relpath)"

.SS "function hashUrl ()"

.SS "function hashValue ()"

.SS "function highlightAnchor ()"

.SS "function initNavTree ( toroot,  relpath)"

.SS "function localStorageSupported ()"

.SS "function navTo ( o,  root,  hash,  relpath)"

.SS "function newNode ( o,  po,  text,  link,  childrenData,  lastNode)"

.SS "function pathName ()"

.SS "function removeToInsertLater ( element)"

.SS "function selectAndHighlight ( hash,  n)"

.SS "function showNode ( o,  node,  index,  hash)"

.SS "function showRoot ()"

.SS "function showSyncOff ( n,  relpath)"

.SS "function showSyncOn ( n,  relpath)"

.SS "function storeLink ( link)"

.SS "function stripPath ( uri)"

.SS "function stripPath2 ( uri)"

.SS "function toggleSyncButton ( relpath)"

.SH "Variable Documentation"
.PP 
.SS "var animationInProgress = false"

.SS "var navTreeSubIndices = new Array()"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
