.TH "C:/wamp/www/ProjetPhp/doc/resize.js" 3 "Sun May 8 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/wamp/www/ProjetPhp/doc/resize.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBreadCookie\fP (cookie)"
.br
.ti -1c
.RI "function \fBwriteCookie\fP (cookie, val, expiration)"
.br
.ti -1c
.RI "function \fBresizeWidth\fP ()"
.br
.ti -1c
.RI "function \fBrestoreWidth\fP (navWidth)"
.br
.ti -1c
.RI "function \fBresizeHeight\fP ()"
.br
.ti -1c
.RI "function \fBinitResizable\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBcookie_namespace\fP = 'doxygen'"
.br
.ti -1c
.RI "var \fBsidenav\fP"
.br
.ti -1c
.RI "var \fBnavtree\fP"
.br
.ti -1c
.RI "var \fBcontent\fP"
.br
.ti -1c
.RI "var \fBheader\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "function initResizable ()"

.SS "function readCookie ( cookie)"

.SS "function resizeHeight ()"

.SS "function resizeWidth ()"

.SS "function restoreWidth ( navWidth)"

.SS "function writeCookie ( cookie,  val,  expiration)"

.SH "Variable Documentation"
.PP 
.SS "var content"

.SS "var cookie_namespace = 'doxygen'"

.SS "var header"

.SS "var navtree"

.SS "var sidenav"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
