.TH "Response" 3 "Sun May 8 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Response \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($survey, $title, $count=0)"
.br
.ti -1c
.RI "\fBsetId\fP ($id)"
.br
.ti -1c
.RI "\fBcomputePercentage\fP ($total)"
.br
.ti -1c
.RI "\fBgetId\fP ()"
.br
.ti -1c
.RI "\fBgetSurvey\fP ()"
.br
.ti -1c
.RI "\fBgetTitle\fP ()"
.br
.ti -1c
.RI "\fBgetCount\fP ()"
.br
.ti -1c
.RI "\fBgetPercentage\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $survey,  $title,  $count = \fC0\fP)"

.SH "Member Function Documentation"
.PP 
.SS "computePercentage ( $total)"

.SS "getCount ()"

.SS "getId ()"

.SS "getPercentage ()"

.SS "getSurvey ()"

.SS "getTitle ()"

.SS "setId ( $id)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
