.TH "SurveysView" 3 "Sun May 8 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SurveysView \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBView\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdisplayBody\fP ()"
.br
.ti -1c
.RI "\fBsetSurveys\fP ($surveys)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "displayBody ()"
Affiche la liste des sondages\&.
.PP
\fBSee also:\fP
.RS 4
\fBView::displayBody()\fP 
.RE
.PP

.SS "setSurveys ( $surveys)"
Envoie les sondages à afficher\&.
.PP
\fBParameters:\fP
.RS 4
\fIarray<Survey>\fP $surveys Sondages à afficher\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
