.TH "Survey" 3 "Sun May 8 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Survey \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($owner, $question)"
.br
.ti -1c
.RI "\fBsetComm\fP ($comm)"
.br
.ti -1c
.RI "\fBgetComm\fP ()"
.br
.ti -1c
.RI "\fBsetId\fP ($id)"
.br
.ti -1c
.RI "\fBgetId\fP ()"
.br
.ti -1c
.RI "\fBgetOwner\fP ()"
.br
.ti -1c
.RI "\fBgetQuestion\fP ()"
.br
.ti -1c
.RI "\fBgetResponses\fP ()"
.br
.ti -1c
.RI "\fBgetVotes\fP ()"
.br
.ti -1c
.RI "\fBgetPercentages\fP ()"
.br
.ti -1c
.RI "\fBsetResponses\fP ($responses)"
.br
.ti -1c
.RI "\fBaddResponse\fP ($response)"
.br
.ti -1c
.RI "\fBaddVote\fP ($vote)"
.br
.ti -1c
.RI "\fBcomputePercentages\fP ($votes)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $owner,  $question)"

.SH "Member Function Documentation"
.PP 
.SS "addResponse ( $response)"

.SS "addVote ( $vote)"

.SS "computePercentages ( $votes)"

.SS "getComm ()"

.SS "getId ()"

.SS "getOwner ()"

.SS "getPercentages ()"

.SS "getQuestion ()"

.SS "getResponses ()"

.SS "getVotes ()"

.SS "setComm ( $comm)"

.SS "setId ( $id)"

.SS "setResponses ( $responses)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
