.TH "C:/wamp/www/ProjetPhp/views/templates/survey.inc.php" 3 "Sun May 8 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/wamp/www/ProjetPhp/views/templates/survey.inc.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$tableauReponses\fP = $survey\->getResponses()"
.br
.ti -1c
.RI "\fB$tableauPctages\fP = $survey\->getPercentages()"
.br
.ti -1c
.RI "for($i=0;$i< count($survey\->getResponses());$i++) \fBif\fP(!isset($_SESSION['afficherCom'])) if($_SESSION['afficherCom']==false) \fBelse\fP {"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$tableauPctages = $survey\->getPercentages()"

.SS "$tableauReponses = $survey\->getResponses()"

.SS "\fBif\fP (isset($_SESSION['login'])) else {"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
