.TH "C:/wamp/www/ProjetPhp/doc/search/variables_1.js" 3 "Sun May 8 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/wamp/www/ProjetPhp/doc/search/variables_1.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['foreach',['foreach',['\&.\&./views_2templates_2_survey_8inc_8php\&.html#a22c3b08d0b374c3d28b3dc18e652db73',1,'survey\&.inc\&.php']]]
]
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
