.TH "View" 3 "Sun May 8 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
View \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAddSurveyFormView\fP, \fBDefaultView\fP, \fBMessageView\fP, \fBSignUpFormView\fP, \fBSurveysView\fP, and \fBUpdateUserFormView\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBrun\fP ()"
.br
.ti -1c
.RI "\fBsetMessage\fP ($message, $style='')"
.br
.ti -1c
.RI "\fBsetLogin\fP ($login)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBdisplayBody\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$message\fP = ''"
.br
.ti -1c
.RI "\fB$style\fP = ''"
.br
.ti -1c
.RI "\fB$login\fP = null"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "displayBody ()\fC [abstract]\fP, \fC [protected]\fP"
Affiche le corps de la page\&. Cette méthode doit être implémentée par les différentes vues\&. 
.SS "run ()"
Génère la page à afficher au client\&. 
.SS "setLogin ( $login)"
Fixe le login de l'utilisateur (s'il est connecté)\&.
.PP
\fBParameters:\fP
.RS 4
\fI$login\fP Login de l'utilisateur\&. 
.RE
.PP

.SS "setMessage ( $message,  $style = \fC''\fP)"
Fixe le message qui doit être affichée par la vue\&.
.PP
\fBParameters:\fP
.RS 4
\fI$message\fP Message à afficher\&. 
.br
\fI$style\fP Style du message à afficher\&. 
.RE
.PP

.SH "Field Documentation"
.PP 
.SS "$login = null\fC [protected]\fP"

.SS "$message = ''\fC [protected]\fP"

.SS "$style = ''\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
